version: '3.8'

services:
  dev-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K1ckdown_
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp:
